from __future__ import annotations
import abc
from pathlib import Path
from ost_explorer.models import Attachment, Contact, Folder, Mailbox, Message

class MailboxParser(abc.ABC):
    @abc.abstractmethod
    def open(self, path: Path) -> Mailbox: ...
    @abc.abstractmethod
    def get_messages(self, folder: Folder, offset: int = 0, limit: int = 50) -> list[Message]: ...
    @abc.abstractmethod
    def get_attachment_bytes(self, attachment: Attachment) -> bytes: ...
    @abc.abstractmethod
    def get_recovered_messages(self) -> list[Message]: ...
    @abc.abstractmethod
    def get_contacts(self) -> list[Contact]: ...
    @abc.abstractmethod
    def close(self) -> None: ...
